fix(migrations): update run order

diff --git a/Dockerfile.migrations b/Dockerfile.migrations
--- a/Dockerfile.migrations
+++ b/Dockerfile.migrations
@@ -1,4 +1,5 @@
 FROM gitlab.polytech.umontpellier.fr:5050/polyflix-do/docker-images/psql-migration:latest
 
-RUN tsc --skipLibCheck true --skipDefaultLibCheck true  ./dist/resources/migrations/*.ts  --outDir "dist/resources/migrations" || echo "expected error"
 COPY ./dist/resources/migrations migrations
+RUN tsc --skipLibCheck true --skipDefaultLibCheck true  ./migrations/*.ts  --outDir "./migrations" || echo "expected error"
+
